spring:
  datasource:
    url: jdbc:postgresql://10.10.80.201/impactplus
    username: root
    password: impactplus
    
       
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  thymeleaf:
    cache: false
    
server:
  port: 8080
